Minimizacion de bandeja de error y arreglo overlay bandeja a lista de curriculumns (PAN-179 PAN-168)
open-source-uc/planner pull request #116
Opened 2023-06-06 03:10 UTC by Diegothx

## Que se implementa?
Ahora se puede minimizar la bandeja de errores y advertencias solo cuando no hay ningún error. Al final me convenci por lo simple y lo deje a traves del tipico boton de 3 lineas de las sidebars.
Está implementado de manera que puedas seguir viendo los iconos de las alertas, así como el icono de carga, (pero este sin mensaje al estar validando). También aproveché para corregir el problema de que los selectores de currículos se estaban renderizando debajo de la bandeja de errores.
## Que falta?
Se necesita alguna forma de identificar rápidamente el curso del error mostrado en la bandeja. Esto quedará para otra rama, ya que requiere su propia lógica. Como idea, estaba pensando en hacer que al hacer hover sobre el error en la bandeja, se "oscurezca" la pantalla excepto el curso asignado. Habría que probar cómo se ve esto. Esto aun le faltaria una forma de identificar rapido los ramos requisitos faltante y esas cosas eso si.

2023-06-06 14:55 UTC, shantifabri requested changes
Me gusta el diseño, pero en mi pantalla se ven cortados los mini warnings y medio desalineado, hay que ver si se puede hacer más responsive (pasa solo cuando me sale ese scroll bar extra)

![image](https://github.com/open-source-uc/planner/assets/37163566/0ed5df6f-3959-4f90-a1c3-0807fba8387e)

2023-06-06 15:06 UTC, Diegothx commented
> Me gusta el diseño, pero en mi pantalla se ven cortados los mini warnings y medio desalineado, hay que ver si se puede hacer más responsive (pasa solo cuando me sale ese scroll bar extra cuando hay muchas advertencias)
> 
> ![image](https://user-images.githubusercontent.com/37163566/243736434-0ed5df6f-3959-4f90-a1c3-0807fba8387e.png)

Wena wena, esto igual es importante porque el scroll es por navegador (so cualquiera con chrome debiera verlo como tu caso).

2023-06-07 05:10 UTC, Diegothx commented
Okey, ya esta arreglado los comentarios!

2023-06-07 13:13 UTC, shantifabri commented
Me pasó esto, queda el loading pegado y no me deja hacer nada, probé en firefox y también pasa.

![loading](https://github.com/open-source-uc/planner/assets/37163566/d09bfc73-4aae-4a31-a6f0-401666496b6a)

2023-06-07 14:01 UTC, Diegothx commented
> Me pasó esto, queda el loading pegado y no me deja hacer nada, probé en firefox y también pasa.
> 
> ![loading](https://user-images.githubusercontent.com/37163566/244070424-d09bfc73-4aae-4a31-a6f0-401666496b6a.gif)

ready tambien, fue un cambio que subi por accidente (estaba tratando de centrar mejor el loading)

2023-06-07 22:33 UTC, shantifabri approved these changes
Buenisima

2023-06-07 22:33 UTC, merged