Arreglos menores (PAN-205 PAN-200 PAN-87 PAN-174)
open-source-uc/planner pull request #160
Opened 2023-06-11 07:03 UTC by Diegothx

### ¿Qué se implementa?
- Se mejora el comportamiento del desplazamiento al arrastrar un curso. Para esto instale una nueva librería so es necesario ejecutar npm install nuevamente en el frontend. La librería utiliza una función para calcular el desplazamiento automático, y por defecto utiliza una función lineal, en un futuro se podría jugar un poco con esto si se quiere.
- Se permite la deselección del título y minor. 
- Se evita bloquear la malla al realizar la validación. Ahora, es posible continuar moviendo los cursos y se cancelará la validación en curso antes de realizará una nueva llamada a la API con la versión actualizada de la malla.
- Se corrige un error al guardar la malla y se restaura la funcionalidad de restablecimiento de la malla.

### Notas
- Considerar en un futuro esperar x segundos antes de hacer una llamada a validar, asi se evita llamar muchas veces a este endpoint y constantemente cancelarse en casos de muchos movimientos seguidos.

2023-06-17 11:40 UTC, shantifabri requested changes
Tengo un par comentarios, 

1) me gusta el poder deseleccionar titulo y minor pero no me gusta la interfaz. Tener que apretar "Por seleccionar" es poco intuitivo, quizás podría quedar la opción fija al inicio de la lista y posiblemente un mejor nombre como por ejemplos "Eliminar selección" o algo así.

2) Al guardar la malla, mientras se da la notificación y se hace el redireccionamiento (o no, si no es la 1era vez que se guarda), aun se pueden hacer cambios que no quedan guardados, creo que mientras se muestra esta notificación puede ser menos confuso que se bloquee la posibilidad hacer cambios, o tal vez simplemente se tendría que hacer la notificación y redireccionamiento más rápidos.

2023-06-19 08:01 UTC, Diegothx commented
> 1. Eliminar selección

Ready lo primero

Sobre lo segundo, en realidad creo que sería mejor cambiarlo y no hacer un redireccionamiento al guardar. Total, ya tenemos la identificación del nuevo plan, así que solo tendríamos que guardar la info de ese plan. Hice un cambio rápido para implementar esto.
 
Esto tambien se justifica mas porque hace rato tengo pendiente un refactor del router, ya que @tanstack/react-router finalmente tiene documentacion mas completa, pero resulta que es de la versión actualizada que funciona de manera muy distinta a la que tenemos, así que tenemos que actualizar el enrutamiento de la App para sacarle provecho.  El cambio principal que le haria es que creo que seria buena idea que en el router mismo se cargue  la data inicial del plan (como estos ejemplos: https://tanstack.com/router/v1/docs/guide/data-loading), ya sea planDefault o PlanById, para que el componente del planner se renderice con un plan ya cargado. Creo que esto simplicaria todos los chequeos molestos de plan nulos (? o por lo menos la logica de carga inicial. Con esto, el plan guardado y el plan nuevo serían accesibles a través de la misma ruta (/planificacion) y solo recibirían los datos de un plan que tenga o no un id.

2023-06-19 16:53 UTC, shantifabri commented
Sobre el selector, se podría hacer que si no hay nada seleccionado no aparezca el eliminar selección? o que esté deshabilitado tal vez? Además creo que podría ser bueno que la opción sea visible incluso al scrolear, aunque su es muy complicado está bien así

2023-06-19 17:51 UTC, Diegothx commented
> Sobre el selector, se podría hacer que si no hay nada seleccionado no aparezca el eliminar selección? o que esté deshabilitado tal vez? Además creo que podría ser bueno que la opción sea visible incluso al scrolear, aunque su es muy complicado está bien así.
> 
> Sobre el guardar malla, me gusta sin redirección, aunque queda el url con "planner/new" pero creo que no es tan terrible.



> Sobre el selector, se podría hacer que si no hay nada seleccionado no aparezca el eliminar selección? o que esté deshabilitado tal vez? Además creo que podría ser bueno que la opción sea visible incluso al scrolear, aunque su es muy complicado está bien así.
> 
> Sobre el guardar malla, me gusta sin redirección, aunque queda el url con "planner/new" pero creo que no es tan terrible.

Ready lo de no mostrar el deseleccionar si no esta seleccionada ninguna opcion. Sobre lo segundo lo implemente tambien pero no se si me convence el dejar el deseleccionar fijo, igual son detalles que se pueden revisar mejor cuando se pruebe la app con mas gente so por ahora dejemoslo fijo y de ahi vemos si queda asi

2023-06-19 18:05 UTC, shantifabri commented
> Ready lo de no mostrar el deseleccionar si no esta seleccionada ninguna opcion. Sobre lo segundo lo implemente tambien pero no se si me convence el dejar el deseleccionar fijo, igual son detalles que se pueden revisar mejor cuando se pruebe la app con mas gente so por ahora dejemoslo fijo y de ahi vemos si queda asi

De acuerdo

2023-06-19 18:06 UTC, shantifabri approved these changes
Approved ✔️

2023-06-19 18:08 UTC, merged