Drag refactor
open-source-uc/planner pull request #198
Opened 2023-06-29 09:18 UTC by Diegothx

# ¿Qué se implementa?

- Mejorar el comportamiento del drag, principalmente no tiene esos taldos que tenia cuando partia el drag. (closes PAN-97).
- Habian partes que no estaban conectadas al router so aproveche de unirlas, ahora no deberia actualizarse la pagina excepto al salir al login
-  Ya se carga la info de los ramos agregados por el auto-fix, 
- Los ultimos 2 semestres ahora siempre se muestran, queda mas comodo a la hora de moverse por la app y minimiza los renderizados. hay que testear si esto es suficiente para que el scroll hacia el ultimo semestre quede bien
- Un poco de re-orden en el frontend, cree en la parte del planner una carpeta utils que planeo delegar hartas funciones para hacer mas legible el archivo principal del planner y mas ordenado todo

# Nota

- Sobre el tema de cargar la info una vez agregado un ramo, dependiendo de que tan costos sea esa llamada quizas podriamos hacer que siempre se llama a la data de los cursos requisitos y todo aquel que aparesca en la bandeja, asi ademas seria facil mostrar sus nombres y todo eso, si es muy pesado hacer estas llamadas extras entonces lo dejaria en que al hacer hover salga un mensajito con el nombre el cual este llamando por detras a los detalles de ese curso

2023-06-29 13:21 UTC, shantifabri commented
Un par de comentarios:

1. El selector de cursos para cursos nuevos dejó de funcionar (y me da la idea de que para equivalencias es más lento)

2. El drag derechamente no funciona en chrome ni edge.

3. Creo que nuevamente hay un espaciamiento mayor entre columnas (tambien puede q sea idea mía, definitivamente no tan relevante).

2023-06-30 21:54 UTC, negamartin commented
Sobre el costo de hacer llamadas a `getCourseDetails`, creo que `getCourseDetails` y `getEquivalenceDetails` son los endpoints menos costosos de toda la API, quizas incluso menos que `health` porque no tocan la base de datos xd

2023-06-30 23:13 UTC, Diegothx commented
> Un par de comentarios:
> 
>     1. El selector de cursos para cursos nuevos dejó de funcionar (y me da la idea de que para equivalencias es más lento)
> 
>     2. El drag derechamente no funciona en chrome ni edge.
> 
>     3. Creo que nuevamente hay un espaciamiento mayor entre columnas (tambien puede q sea idea mía, definitivamente no tan relevante).

1)No cache que tiene que ver esto con esta rama

2023-06-30 23:16 UTC, Diegothx commented
No queria cerrarla xd, 

> Un par de comentarios:
> 
>     1. El selector de cursos para cursos nuevos dejó de funcionar (y me da la idea de que para equivalencias es más lento)
> 
>     2. El drag derechamente no funciona en chrome ni edge.
> 
>     3. Creo que nuevamente hay un espaciamiento mayor entre columnas (tambien puede q sea idea mía, definitivamente no tan relevante).

Yap yap, se me ocurre que puede estar fallando en ambos casos so el sabado los arreglo

2023-07-02 07:10 UTC, Diegothx commented
> Un par de comentarios:
> 
>     1. El selector de cursos para cursos nuevos dejó de funcionar (y me da la idea de que para equivalencias es más lento)
> 
>     2. El drag derechamente no funciona en chrome ni edge.
> 
>     3. Creo que nuevamente hay un espaciamiento mayor entre columnas (tambien puede q sea idea mía, definitivamente no tan relevante).

Arreglado lo de chrome, edge, el selector que habia dejado de funcionar (y el ancho).
Sobre lo de la lentitud para las equivalencias la verdad no se, por lo menos de forma directa no le hice ningun cambio a ese componente pero es verdad que tiene un delay para abrir (que supongo que es a lo que te refieres), aunque sinceramente no recuerdo si antes era asi o no. Aparentemente mas alla del llamado a la data de la equivalencia y al propio renderizado del modal no se me ocurre otro posible cuello de botella. Una opcion que se me ocurre es que realmente no estamos usando directamente la lista de cursos de la equivalencia, de echo de esta solo ocupamos su codigo y su nombre, debido a que apenas abrimos el modal hacemos una llamada con filtro para colocar solo los disponibles, por lo cual quizas podriamos hacer un light_request_equivalence? u algo asi que solo nos retorne nombre y codigo.

2023-07-02 07:16 UTC, Diegothx commented
> Sobre el costo de hacer llamadas a `getCourseDetails`, creo que `getCourseDetails` y `getEquivalenceDetails` son los endpoints menos costosos de toda la API, quizas incluso menos que `health` porque no tocan la base de datos xd

wena wena, lo tendre en cuenta entonces

2023-07-02 07:22 UTC, Diegothx commented
> Sobre el costo de hacer llamadas a `getCourseDetails`, creo que `getCourseDetails` y `getEquivalenceDetails` son los endpoints menos costosos de toda la API, quizas incluso menos que `health` porque no tocan la base de datos xd

De echo getEquivalenceDetails podria ser incluso menos costosa, sino me equivoco en ningun lado estamos usando los codigos posibles de esta, porque en el selector al tiro usa el codigo de la equivalencia para filtrar a cursos disponibles, so a menos que terminaramos haciendo la idea de mover el filtro al frontend llamando a toda la data entonces quizas el getEquivalenceDetails podria solo retornar el nombre, el codigo y esas cosas.

2023-07-02 14:52 UTC, shantifabri commented
Lo arreglado funciona todo bien. Sobre lo de las equivalencias no se por qué ese día que revisé andaba lento jajaj pero todo ok ahora.

Me fijé ahora que los cursos reprobados aparecen así solo con #FAILED en la tarjeta, sin nombre ni nada de info.

![image](https://github.com/open-source-uc/planner/assets/37163566/6a9746af-81ac-43a2-b825-47e2b19f5f0a)

2023-07-02 16:07 UTC, Diegothx commented
> Lo arreglado funciona todo bien. Sobre lo de las equivalencias no se por qué ese día que revisé andaba lento jajaj pero todo ok ahora.
> 
> Me fijé ahora que los cursos reprobados aparecen así solo con #FAILED en la tarjeta, sin nombre ni nada de info.
> 
> ![image](https://user-images.githubusercontent.com/37163566/250364499-6a9746af-81ac-43a2-b825-47e2b19f5f0a.png)

ready!

2023-07-03 10:31 UTC, shantifabri requested changes
Duda, el que quede con el #FAILED en vez de la sigla es intencional? 

![image](https://github.com/open-source-uc/planner/assets/37163566/06acdade-85f1-461d-baf4-5b8768a5905e)

Creo que la sigla es importante por que a veces cursos se llaman igual pero tienen distinta sigla.

2023-07-03 15:16 UTC, negamartin commented
Estuve leyendo los cambios, y me encanta este reorden, es todo lo que no sabia que queria ordenar en el frontend. Capaz con esto podemos eliminar el planDigest y validationDigest y reemplazarlos por funciones de utilidad posiblemente cacheadas.

Lo único, sería extra cuidadoso al mergear esta branch con main, porque tiene hartas diferencias "estructurales". Lo digo porque lo de los ramos echados ya estaba en main, y se debe haber perdido en algun merge.

2023-07-03 15:18 UTC, negamartin commented on frontend/src/contexts/auth.context.tsx
> +        toast.error('Tu session a expirado. Redireccionando a pagina de inicio de sesion...', {
Acá debiera ser "Tu sesión ha expirado. Redireccionando a página de inicio de sesión..."

2023-07-03 15:34 UTC, agucova commented on frontend/vite.config.ts.timestamp-1687829809456-5a4e5b3dceabc.mjs
> +import { defineConfig } from "file:///workspaces/planner/frontend/node_modules/vite/dist/node/index.js";
Este archivo no debiese estar acá, probablemente es un artifact de un build que crashó.

2023-07-03 20:46 UTC, Diegothx commented
> Duda, el que quede con el #FAILED en vez de la sigla es intencional?
> 
> ![image](https://user-images.githubusercontent.com/37163566/250531236-06acdade-85f1-461d-baf4-5b8768a5905e.png)
> 
> Creo que la sigla es importante por que a veces cursos se llaman igual pero tienen distinta sigla.

arreglado eso

2023-07-03 21:02 UTC, Diegothx commented
> > Duda, el que quede con el #FAILED en vez de la sigla es intencional?
> > ![image](https://user-images.githubusercontent.com/37163566/250531236-06acdade-85f1-461d-baf4-5b8768a5905e.png)
> > Creo que la sigla es importante por que a veces cursos se llaman igual pero tienen distinta sigla.
> 
> arreglado eso



> Estuve leyendo los cambios, y me encanta este reorden, es todo lo que no sabia que queria ordenar en el frontend. Capaz con esto podemos eliminar el planDigest y validationDigest y reemplazarlos por funciones de utilidad posiblemente cacheadas.
> 
> Lo único, sería extra cuidadoso al mergear esta branch con main, porque tiene hartas diferencias "estructurales". Lo digo porque lo de los ramos echados ya estaba en main, y se debe haber perdido en algun merge.

si hacia falta la verdad jajaja, llevaba harto rato viendo como deberia estructurar correctamente el codigo, pero me termino tomando harto mas tiempo del que planeaba (y aun se puede seguir haciendo cosas, solo que por alcnace lo deje hasta aca por ahora)

2023-07-05 02:40 UTC, merged